# based on https://stackoverflow.com/a/64373702

name: Docker build and deploy
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Build the docker image and run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose build web

    - name: Run tests
      run: |
        docker-compose build test
        docker-compose run test

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Push to DockerHub
      run: docker push holgergraef/msm

    - name: Login to ghcr
      run: echo ${{ github.token }} | docker login ghcr.io -u HolgerGraef --password-stdin

    - name: Push to ghcr
      run: docker push ghcr.io/HolgerGraef/msm:latest
